model: Resnet18
model_params:
    experiment_name: cifar10_with_resnet18
    seed: 1
data_augmentation:
    type: CIFAR10Albumentation
    data_augment:
    minHeight : 36
    minWidth : 36
    height : 32
    width : 32
    horizontalFlipProb : 0.2
    num_holes : 1
    max_h_size : 8
    max_w_size : 8
    grayscaleProb : 0.15
data_loader:
    type: Cifar10DataLoader
    classes: ['plane', 'car', 'bird', 'cat', 'deer', 'dog', 'frog', 'horse', 'ship', 'truck']
    args:
        batch_size: 512
        num_workers: 2
        pin_memory: true
criterion: CrossEntropyLoss
optimizer : 
    type: optim.Adam
    args:
        lr: 0.01
lr_scheduler: OneCycleLR
max_lr_epoch : 5

training_params:
    epochs: 20
